- hosts: servidores
  become: yes
  tasks:
    - name: Actualizar la caché de apt
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Instalar Cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear un archivo
      file:
        path: /home/vagrant/archivo.txt
        state: touch

    - name: Copiar archivos
      copy:
        src: /ruta/al/archivo_fuente
        dest: /home/vagrant/

    - name: Crear carpetas
      file:
        path: /home/vagrant/carpeta
        state: directory

    - name: Iniciar el servicio Apache
      service:
        name: apache2
        state: started

    - name: Agregar un usuario
      user:
        name: nuevo_usuario
        state: present

    - name: Ejecutar un script en el servidor
      command: /home/vagrant/mi_script.sh
